# Generated by Django 5.2.9 on 2026-01-19 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paniers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlepanier',
            name='prix',
        ),
    ]
