# Generated by Django 5.2.9 on 2026-01-19 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paniers', '0002_remove_articlepanier_prix'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepanier',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
