# Generated by Django 5.2.9 on 2026-01-17 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='nom',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Titre du produit'),
        ),
    ]
