# Generated by Django 5.2.9 on 2026-01-04 09:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Boutique',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=200, unique=True, verbose_name='Nom de la boutique')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('description', models.TextField(verbose_name='Description')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='boutiques/logos/', verbose_name='Logo')),
                ('banniere', models.ImageField(blank=True, null=True, upload_to='boutiques/bannieres/', verbose_name='Bannière')),
                ('secteur_activite', models.CharField(max_length=100, verbose_name="Secteur d'activité")),
                ('adresse', models.TextField(verbose_name='Adresse')),
                ('ville', models.CharField(max_length=100, verbose_name='Ville')),
                ('telephone', models.CharField(max_length=15, verbose_name='Téléphone')),
                ('email', models.EmailField(max_length=254, verbose_name='Email de contact')),
                ('site_web', models.URLField(blank=True, verbose_name='Site web')),
                ('facebook', models.URLField(blank=True, verbose_name='Facebook')),
                ('instagram', models.URLField(blank=True, verbose_name='Instagram')),
                ('twitter', models.URLField(blank=True, verbose_name='Twitter')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente de validation'), ('ACTIVE', 'Active'), ('SUSPENDUE', 'Suspendue'), ('FERMEE', 'Fermée')], default='EN_ATTENTE', max_length=20, verbose_name='Statut')),
                ('est_premium', models.BooleanField(default=False, verbose_name='Compte premium')),
                ('premium_expire_le', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('validee_le', models.DateTimeField(blank=True, null=True, verbose_name='Date devalidation')),
                ('validee_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boutiques_validees', to=settings.AUTH_USER_MODEL, verbose_name='Validée par')),
                ('vendeur', models.OneToOneField(limit_choices_to={'type_utilisateur': 'VENDEUR'}, on_delete=django.db.models.deletion.CASCADE, related_name='boutique', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Boutique',
                'verbose_name_plural': 'Boutiques',
                'ordering': ['-created_at'],
            },
        ),
    ]
