# Generated by Django 5.2.9 on 2026-01-11 08:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutiques', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boutique',
            name='nom',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='Nom de la boutique'),
        ),
        migrations.AlterField(
            model_name='boutique',
            name='validee_le',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de validation'),
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100, unique=True, verbose_name='Nom')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('icone', models.CharField(blank=True, default='fa-tag', max_length=50)),
                ('ordre', models.IntegerField(default=0, verbose_name='Ordre')),
                ('est_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sous_categories', to='boutiques.categorie', verbose_name='Catégorie parente')),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.AddField(
            model_name='boutique',
            name='categories',
            field=models.ManyToManyField(related_name='boutiques', to='boutiques.categorie', verbose_name='Catégories de produits'),
        ),
    ]
