# Generated by Django 5.2.9 on 2026-01-17 19:40

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutiques', '0002_alter_boutique_nom_alter_boutique_validee_le_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AvisBoutique',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('note', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Note')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('commentaire', models.TextField(verbose_name='Commentaire')),
                ('note_produits', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Note produits')),
                ('note_service', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Note service')),
                ('note_livraison', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Note livraison')),
                ('est_publie', models.BooleanField(default=True, verbose_name='Publié')),
                ('est_verifie', models.BooleanField(default=False, verbose_name='Achat vérifié')),
                ('reponse', models.TextField(blank=True, verbose_name='Réponse du vendeur')),
                ('repondu_le', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('boutique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avis', to='boutiques.boutique', verbose_name='Boutique')),
                ('client', models.ForeignKey(limit_choices_to={'user_type': 'ACHETEUR'}, on_delete=django.db.models.deletion.CASCADE, related_name='avis_boutiques', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Avis boutique',
                'verbose_name_plural': 'Avis boutiques',
                'ordering': ['-created_at'],
                'unique_together': {('boutique', 'client')},
            },
        ),
        migrations.CreateModel(
            name='StatistiqueBoutique',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='Date')),
                ('vues_boutique', models.IntegerField(default=0, verbose_name='Vues boutique')),
                ('vues_produits', models.IntegerField(default=0, verbose_name='Vues produits')),
                ('nombre_commandes', models.IntegerField(default=0, verbose_name='Nombre de commandes')),
                ('chiffre_affaires', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name="Chiffre d'affaires")),
                ('nouveaux_followers', models.IntegerField(default=0, verbose_name='Nouveaux followers')),
                ('messages_recus', models.IntegerField(default=0, verbose_name='Messages reçus')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('boutique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistiques', to='boutiques.boutique')),
            ],
            options={
                'verbose_name': 'Statistique boutique',
                'verbose_name_plural': 'Statistiques boutiques',
                'ordering': ['-date'],
                'unique_together': {('boutique', 'date')},
            },
        ),
        migrations.CreateModel(
            name='SuiviBoutique',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notifications_nouveaux_produits', models.BooleanField(default=True, verbose_name='Notifications nouveaux produits')),
                ('notifications_promotions', models.BooleanField(default=True, verbose_name='Notifications promotions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('boutique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='boutiques.boutique')),
                ('client', models.ForeignKey(limit_choices_to={'user_type': 'ACHETEUR'}, on_delete=django.db.models.deletion.CASCADE, related_name='boutiques_suivies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Suivi de boutique',
                'verbose_name_plural': 'Suivis de boutiques',
                'ordering': ['-created_at'],
                'unique_together': {('client', 'boutique')},
            },
        ),
    ]
